apiVersion: v1
kind: ConfigMap

metadata:
  name: finstream-config
  namespace: finstream

data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_TOPIC: "transactions"
  KAFKA_DLQ_TOPIC: "transactions.dlq"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "finstream"
