apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: finstream
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      terminationGracePeriodSeconds: 30

      containers:
        - name: processor
          image: finstream-processor:dev
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL


          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          env:
            - name: PYTHONUNBUFFERED
              value: "1"

          envFrom:
            - configMapRef:
                name: finstream-config
            - secretRef:
                name: finstream-secret
