apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: finstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: processor
          image: finstream-processor:dev
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          env:
            - name: PYTHONUNBUFFERED
              value: "1"

          envFrom:
            - configMapRef:
                name: finstream-config
            - secretRef:
                name: finstream-secret
