apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: finstream
spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      terminationGracePeriodSeconds: 30

      containers:
        - name: producer
          image: finstream-producer:dev
          imagePullPolicy: IfNotPresent

          ports:
            - name: metrics
              containerPort: 8001

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL


          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

          env:
            - name: PYTHONUNBUFFERED
              value: "1"

            - name: METRICS_PORT
              value: "8001"

          envFrom:
            - configMapRef:
                name: finstream-config

---
apiVersion: v1
kind: Service

metadata:
  name: producer-metrics
  namespace: finstream

spec:
  selector:
    app: producer

  ports:
    - name: metrics
      port: 8001
      targetPort: metrics
      protocol: TCP

  type: ClusterIP
