apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-config
  namespace: finstream

data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: finstream-api
        metrics_path: /metrics
        static_configs:
          - targets:
              - api:8000

      - job_name: finstream-producer
        metrics_path: /metrics
        static_configs:
          - targets:
              - producer-metrics:8001

      - job_name: finstream-processor
        metrics_path: /metrics
        static_configs:
          - targets:
              - processor-metrics:8002
