from prometheus_client import Counter

TRANSACTIONS_GENERATED_TOTAL = Counter(
    "finstream_producer_transactions_generated_total",
    "Total number of transactions generated by FinStream.",
    ["suspicious"],
)


TRANSACTIONS_PUBLISHED_TOTAL = Counter(
    "finstream_producer_transactions_published_total",
    "Total number of transactions successfully delivered to Kafka.",
)


DELIVERY_FAILURES_TOTAL = Counter(
    "finstream_producer_delivery_failures_total",
    "Total number of transaction delivery failures reported by Kafka.",
)


def record_generated_transaction(transaction):
    suspicious = str(bool(transaction["suspicious"])).lower()

    TRANSACTIONS_GENERATED_TOTAL.labels(
        suspicious=suspicious,
    ).inc()
